name: cex
version: '3.8'

services:
  # 1. Redis Cache Service
  redis:
    image: redis:alpine3.20
    container_name: cex-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cex-network

  # 2. PostgreSQL Database Service
  postgres:
    image: postgres:16.9-alpine
    container_name: cex-postgres
    restart: always
    ports:
      - "5432:5432" # Keeps host port 8080 open for your local Prisma/Backend connection
    environment:
      POSTGRES_USER: cexadmin
      POSTGRES_PASSWORD: alan@admin
      POSTGRES_DB: cex_database
    volumes:
      - cex-db-data:/var/lib/postgresql/data
    networks:
      - cex-network

  # 3. Web-based pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cex-pgadmin
    restart: always
    ports:
      - "5050:80" # Maps port 5050 on your machine to the pgAdmin web server
    environment:
      PGADMIN_DEFAULT_EMAIL: bdev1dmin@cex.com   # Web login email
      PGADMIN_DEFAULT_PASSWORD: bdev1alan # Web login password
    volumes:
      - cex-pgadmin-data:/var/lib/pgadmin     # Saves your pgAdmin server connections
    networks:
      - cex-network
    depends_on:
      - postgres # Tells Docker to start PostgreSQL first

# Networks for internal service-to-service communication
networks:
  cex-network:
    driver: bridge

# Volumes for hard drive data persistence
volumes:
  cex-db-data:
  cex-pgadmin-data: